/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

/**
 *
 * @author Deepak
 */
import java.sql.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class OwnerForm extends javax.swing.JFrame {

    /**
     * Creates new form OwnerForm
     */
    public OwnerForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonPanels = new javax.swing.JPanel();
        changePassButton = new javax.swing.JButton();
        viewPurcButton = new javax.swing.JButton();
        viewSaleButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        profButton = new javax.swing.JButton();
        stocButton = new javax.swing.JButton();
        suppButton = new javax.swing.JButton();
        subPanels = new javax.swing.JPanel();
        roughPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        changePassPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newPasswordField = new javax.swing.JPasswordField();
        oldPasswordField = new javax.swing.JPasswordField();
        confPasswordField = new javax.swing.JPasswordField();
        smButton = new javax.swing.JButton();
        spButton = new javax.swing.JButton();
        selfButton = new javax.swing.JButton();
        viewPurcPanel = new javax.swing.JPanel();
        ptransLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ptransTable = new javax.swing.JTable();
        pfromdateTF = new javax.swing.JTextField();
        pfromLabel = new javax.swing.JLabel();
        ptoLabel = new javax.swing.JLabel();
        ptodateTF = new javax.swing.JTextField();
        psearchButton = new javax.swing.JButton();
        pviewAllButton = new javax.swing.JButton();
        pviewDetailsButton = new javax.swing.JButton();
        viewSalePanel = new javax.swing.JPanel();
        stransLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        stransTable = new javax.swing.JTable();
        sfromdateTF = new javax.swing.JTextField();
        sfromLabel = new javax.swing.JLabel();
        stoLabel = new javax.swing.JLabel();
        stodateTF = new javax.swing.JTextField();
        ssearchButton = new javax.swing.JButton();
        sviewAllButton = new javax.swing.JButton();
        sviewDetailsButton = new javax.swing.JButton();
        profPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        passTF = new javax.swing.JTextField();
        stocPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        fsButton = new javax.swing.JButton();
        lsButton = new javax.swing.JButton();
        stockLabel = new javax.swing.JLabel();
        suppPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("**********Owner**********");

        buttonPanels.setBackground(new java.awt.Color(153, 0, 0));
        buttonPanels.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));

        changePassButton.setBackground(new java.awt.Color(255, 153, 51));
        changePassButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 16)); // NOI18N
        changePassButton.setText("Change Password");
        changePassButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        changePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassButtonActionPerformed(evt);
            }
        });

        viewPurcButton.setBackground(new java.awt.Color(255, 153, 51));
        viewPurcButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        viewPurcButton.setText("Veiw Purchase");
        viewPurcButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewPurcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPurcButtonActionPerformed(evt);
            }
        });

        viewSaleButton.setBackground(new java.awt.Color(255, 153, 51));
        viewSaleButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        viewSaleButton.setText("View Sale");
        viewSaleButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        viewSaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSaleButtonActionPerformed(evt);
            }
        });

        logButton.setBackground(new java.awt.Color(255, 153, 51));
        logButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        logButton.setText("logout");
        logButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logButton.setMaximumSize(new java.awt.Dimension(100, 100));
        logButton.setMinimumSize(new java.awt.Dimension(100, 100));
        logButton.setPreferredSize(new java.awt.Dimension(100, 100));
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        profButton.setBackground(new java.awt.Color(255, 153, 51));
        profButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        profButton.setText("Profile");
        profButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profButton.setMaximumSize(new java.awt.Dimension(100, 100));
        profButton.setMinimumSize(new java.awt.Dimension(100, 100));
        profButton.setPreferredSize(new java.awt.Dimension(100, 100));
        profButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profButtonActionPerformed(evt);
            }
        });

        stocButton.setBackground(new java.awt.Color(255, 153, 51));
        stocButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        stocButton.setText("Stock");
        stocButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stocButton.setMaximumSize(new java.awt.Dimension(100, 100));
        stocButton.setMinimumSize(new java.awt.Dimension(100, 100));
        stocButton.setPreferredSize(new java.awt.Dimension(100, 100));
        stocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocButtonActionPerformed(evt);
            }
        });

        suppButton.setBackground(new java.awt.Color(255, 153, 51));
        suppButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        suppButton.setText("Supplier");
        suppButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        suppButton.setMaximumSize(new java.awt.Dimension(100, 100));
        suppButton.setMinimumSize(new java.awt.Dimension(100, 100));
        suppButton.setPreferredSize(new java.awt.Dimension(100, 100));
        suppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelsLayout = new javax.swing.GroupLayout(buttonPanels);
        buttonPanels.setLayout(buttonPanelsLayout);
        buttonPanelsLayout.setHorizontalGroup(
            buttonPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelsLayout.createSequentialGroup()
                .addGroup(buttonPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelsLayout.createSequentialGroup()
                        .addContainerGap(17, Short.MAX_VALUE)
                        .addComponent(viewPurcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buttonPanelsLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(buttonPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(suppButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewSaleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(changePassButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(profButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stocButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        buttonPanelsLayout.setVerticalGroup(
            buttonPanelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(profButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(stocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(suppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changePassButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewPurcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewSaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        subPanels.setBackground(new java.awt.Color(153, 0, 0));
        subPanels.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        subPanels.setLayout(new java.awt.CardLayout());

        roughPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Welcome");

        javax.swing.GroupLayout roughPanelLayout = new javax.swing.GroupLayout(roughPanel);
        roughPanel.setLayout(roughPanelLayout);
        roughPanelLayout.setHorizontalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roughPanelLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        roughPanelLayout.setVerticalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roughPanelLayout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        subPanels.add(roughPanel, "card2");

        changePassPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("New password:");

        jLabel4.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Old password:");

        jLabel5.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Confirm password:");

        newPasswordField.setText("jPasswordField1");

        oldPasswordField.setText("jPasswordField2");

        confPasswordField.setText("jPasswordField3");

        smButton.setBackground(new java.awt.Color(255, 102, 0));
        smButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        smButton.setText("Stock Manager");
        smButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        smButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smButtonActionPerformed(evt);
            }
        });

        spButton.setBackground(new java.awt.Color(255, 102, 0));
        spButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        spButton.setText("Sales Person");
        spButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        spButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spButtonActionPerformed(evt);
            }
        });

        selfButton.setBackground(new java.awt.Color(255, 102, 0));
        selfButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        selfButton.setText("Self");
        selfButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        selfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changePassPanelLayout = new javax.swing.GroupLayout(changePassPanel);
        changePassPanel.setLayout(changePassPanelLayout);
        changePassPanelLayout.setHorizontalGroup(
            changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(oldPasswordField)
                    .addComponent(confPasswordField))
                .addGap(120, 120, 120))
            .addGroup(changePassPanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(smButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(selfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(spButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changePassPanelLayout.setVerticalGroup(
            changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePassPanelLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePassPanelLayout.createSequentialGroup()
                        .addComponent(newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(confPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changePassPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addGap(68, 68, 68)
                .addGroup(changePassPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(smButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(126, Short.MAX_VALUE))
        );

        subPanels.add(changePassPanel, "card2");

        viewPurcPanel.setBackground(new java.awt.Color(153, 0, 0));

        ptransLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        ptransLabel.setForeground(new java.awt.Color(255, 102, 0));
        ptransLabel.setText("Purchase Transactions");

        ptransTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "transaction ID", "Puchase Date", "Total Cast"
            }
        ));
        jScrollPane4.setViewportView(ptransTable);

        pfromdateTF.setText("yyyy-mm-dd");

        pfromLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        pfromLabel.setForeground(new java.awt.Color(255, 102, 0));
        pfromLabel.setText("From");

        ptoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ptoLabel.setForeground(new java.awt.Color(255, 102, 0));
        ptoLabel.setText("To");

        ptodateTF.setText("yyyy-mm-dd");
        ptodateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptodateTFActionPerformed(evt);
            }
        });

        psearchButton.setText("search");
        psearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psearchButtonActionPerformed(evt);
            }
        });

        pviewAllButton.setText("View All");
        pviewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pviewAllButtonActionPerformed(evt);
            }
        });

        pviewDetailsButton.setText("View Details");
        pviewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pviewDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewPurcPanelLayout = new javax.swing.GroupLayout(viewPurcPanel);
        viewPurcPanel.setLayout(viewPurcPanelLayout);
        viewPurcPanelLayout.setHorizontalGroup(
            viewPurcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPurcPanelLayout.createSequentialGroup()
                .addGroup(viewPurcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewPurcPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(viewPurcPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(viewPurcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ptransLabel)
                            .addGroup(viewPurcPanelLayout.createSequentialGroup()
                                .addComponent(pfromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(ptoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ptodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(psearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(pviewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(viewPurcPanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(pviewDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewPurcPanelLayout.setVerticalGroup(
            viewPurcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewPurcPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(ptransLabel)
                .addGap(18, 18, 18)
                .addGroup(viewPurcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfromLabel)
                    .addComponent(ptoLabel)
                    .addComponent(ptodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(psearchButton)
                    .addComponent(pviewAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pviewDetailsButton)
                .addGap(28, 28, 28))
        );

        subPanels.add(viewPurcPanel, "card2");

        viewSalePanel.setBackground(new java.awt.Color(153, 0, 0));

        stransLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        stransLabel.setForeground(new java.awt.Color(255, 102, 0));
        stransLabel.setText("Sale Transactions");

        stransTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "transaction ID", "Puchase Date", "Total Cast"
            }
        ));
        jScrollPane5.setViewportView(stransTable);

        sfromdateTF.setText("yyyy-mm-dd");

        sfromLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sfromLabel.setForeground(new java.awt.Color(255, 102, 0));
        sfromLabel.setText("From");

        stoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stoLabel.setForeground(new java.awt.Color(255, 102, 0));
        stoLabel.setText("To");

        stodateTF.setText("yyyy-mm-dd");
        stodateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stodateTFActionPerformed(evt);
            }
        });

        ssearchButton.setText("search");
        ssearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssearchButtonActionPerformed(evt);
            }
        });

        sviewAllButton.setText("View All");
        sviewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sviewAllButtonActionPerformed(evt);
            }
        });

        sviewDetailsButton.setText("View Details");
        sviewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sviewDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewSalePanelLayout = new javax.swing.GroupLayout(viewSalePanel);
        viewSalePanel.setLayout(viewSalePanelLayout);
        viewSalePanelLayout.setHorizontalGroup(
            viewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSalePanelLayout.createSequentialGroup()
                .addGroup(viewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewSalePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(viewSalePanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(viewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(viewSalePanelLayout.createSequentialGroup()
                                .addComponent(sfromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(stoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ssearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewSalePanelLayout.createSequentialGroup()
                                .addComponent(stransLabel)
                                .addGap(37, 37, 37)))
                        .addGap(14, 14, 14)
                        .addComponent(sviewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(viewSalePanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(sviewDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        viewSalePanelLayout.setVerticalGroup(
            viewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSalePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stransLabel)
                .addGap(20, 20, 20)
                .addGroup(viewSalePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfromLabel)
                    .addComponent(stoLabel)
                    .addComponent(stodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssearchButton)
                    .addComponent(sviewAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sviewDetailsButton)
                .addGap(28, 28, 28))
        );

        subPanels.add(viewSalePanel, "card2");

        profPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 51));
        jLabel7.setText("Name");

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 51));
        jLabel8.setText("ID");

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 51));
        jLabel9.setText("Password");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profPanelLayout = new javax.swing.GroupLayout(profPanel);
        profPanel.setLayout(profPanelLayout);
        profPanelLayout.setHorizontalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        profPanelLayout.setVerticalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nameTF))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
        );

        subPanels.add(profPanel, "card2");

        stocPanel.setBackground(new java.awt.Color(153, 0, 0));

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Type", "Buying Price", "Selling Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(pTable);

        fsButton.setText("View Full Stock");
        fsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsButtonActionPerformed(evt);
            }
        });

        lsButton.setText("Least Stock");
        lsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsButtonActionPerformed(evt);
            }
        });

        stockLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        stockLabel.setForeground(new java.awt.Color(255, 102, 0));
        stockLabel.setText("Stock");

        javax.swing.GroupLayout stocPanelLayout = new javax.swing.GroupLayout(stocPanel);
        stocPanel.setLayout(stocPanelLayout);
        stocPanelLayout.setHorizontalGroup(
            stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stocPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stockLabel)
                .addGap(230, 230, 230))
        );
        stocPanelLayout.setVerticalGroup(
            stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(stockLabel)
                .addGap(18, 18, 18)
                .addGroup(stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fsButton)
                    .addComponent(lsButton))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        subPanels.add(stocPanel, "card2");

        suppPanel.setBackground(new java.awt.Color(153, 0, 0));

        suppTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier name", "Address", "Phone no#", "City", "Country", "Email ID"
            }
        ));
        jScrollPane2.setViewportView(suppTable);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 51));
        jLabel10.setText("**********Suppliers**********");

        javax.swing.GroupLayout suppPanelLayout = new javax.swing.GroupLayout(suppPanel);
        suppPanel.setLayout(suppPanelLayout);
        suppPanelLayout.setHorizontalGroup(
            suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppPanelLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(76, 76, 76))
            .addGroup(suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(suppPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2)
                    .addContainerGap()))
        );
        suppPanelLayout.setVerticalGroup(
            suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
            .addGroup(suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppPanelLayout.createSequentialGroup()
                    .addContainerGap(61, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(31, 31, 31)))
        );

        subPanels.add(suppPanel, "card2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonPanels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonPanels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subPanels, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            close();
            login loge = new login();
            loge.setVisible(true);
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Login foem can't be opened.");
        }
    }//GEN-LAST:event_logButtonActionPerformed

    private void profButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(profPanel);
        subPanels.repaint();
        subPanels.revalidate();
        addProfFields();
    }//GEN-LAST:event_profButtonActionPerformed
    public void addProfFields()
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= con.createStatement();
            String qry = "select * from user where type = 'Owner'";
            ResultSet rs = st.executeQuery(qry);
            rs.next();
            String uid=rs.getString("uID"); 
            String uname=rs.getString("uname");
            String pass=rs.getString("password");
            nameTF.setText(uname);
            idTF.setText(uid);
            passTF.setText(pass);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    private void stocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(stocPanel);
        subPanels.repaint();
        subPanels.revalidate();

    }//GEN-LAST:event_stocButtonActionPerformed

    private void suppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(suppPanel);
        subPanels.repaint();
        subPanels.revalidate();
        fillSuppTable();
    }//GEN-LAST:event_suppButtonActionPerformed
    public void fillSuppTable()
    {
        DefaultTableModel model = (DefaultTableModel) suppTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from supplier;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String sid=rs.getString("sID");
                String sname=rs.getString("sname");
                String address=rs.getString("address");
                String phone=rs.getString("phone");
                String city=rs.getString("city");
                String country=rs.getString("country");
                String email=rs.getString("email");
                
                model.addRow(new Object[]{sid,sname,address,phone,city,country,email});
            }
            rs.close();
            st.close();
            conn.close();   
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"error in connection");
        }
    }
    private void smButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smButtonActionPerformed
        // TODO add your handling code here:
        String oldpass = oldPasswordField.getText();
        String newpass = newPasswordField.getText();
        String confpass = confPasswordField.getText();
        boolean isNewMatch = false;
        if(newpass != null && confpass != null)
        {
            if((newpass.equals(confpass)))
                {
                isNewMatch = true;
                try
                {
                    Class.forName("java.sql.Driver");
                    Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
                    Statement st= conn.createStatement();
                    String qry = "select password from user where type = 'Stock Manager' ;";
                    ResultSet rs = st.executeQuery(qry);
                    rs.next();
                    String pass = rs.getString("password");
                    if(isNewMatch)
                    {
                        if(oldpass.equals(pass))
                        {
                            Statement st1= conn.createStatement();
                            String qry1 = "update user set password = '"+newpass+"' where type = 'Stock Manager' ;";
                            st1.executeUpdate(qry1);
                            st1.close();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this,"Invalid Old Password");
                        }
                    }
                    rs.close();
                    st.close();
                    conn.close();
                    JOptionPane.showMessageDialog(this,"Password reset successfully");

                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(this,"error in connection");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Password Does not Match.\n! Enter New Password Again");
            }
        }
        else
            {
                JOptionPane.showMessageDialog(this,"Empty Password Field");
            }
    }//GEN-LAST:event_smButtonActionPerformed

    private void ptodateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptodateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptodateTFActionPerformed

    private void psearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psearchButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) ptransTable.getModel();
        String from = pfromdateTF.getText();
        String to = ptodateTF.getText();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from purchase_order where purchase_date between "+
            "'"+from+"' and "+"'"+to+"' order by purchase_date asc;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("ptID");
                String date = rs.getString("purchase_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
            JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        }
    }//GEN-LAST:event_psearchButtonActionPerformed

    private void pviewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pviewAllButtonActionPerformed
        // TODO add your handling code here:

        DefaultTableModel model = (DefaultTableModel) ptransTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from purchase_order order by ptID;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("ptID");
                String date = rs.getString("purchase_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
            JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        }
    }//GEN-LAST:event_pviewAllButtonActionPerformed

    private void pviewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pviewDetailsButtonActionPerformed
        // TODO add your handling code here:
        viewPTransactionDetails ptd = new viewPTransactionDetails();
        ptd.setVisible(true);

    }//GEN-LAST:event_pviewDetailsButtonActionPerformed

    private void stodateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stodateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stodateTFActionPerformed

    private void ssearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssearchButtonActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) stransTable.getModel();
        String from = sfromdateTF.getText();
        String to = stodateTF.getText();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from sale_order where sale_date between "+
                    "'"+from+"' and "+"'"+to+"' order by sale_date asc;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("stID");
                String date = rs.getString("sale_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            //JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        } 
    }//GEN-LAST:event_ssearchButtonActionPerformed

    private void sviewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sviewAllButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) stransTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from sale_order order by stID;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("stID");
                String date = rs.getString("sale_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            //JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_sviewAllButtonActionPerformed

    private void sviewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sviewDetailsButtonActionPerformed
        // TODO add your handling code here:
        viewSTransactionDetails1 std = new viewSTransactionDetails1();
        std.setVisible(true);
    }//GEN-LAST:event_sviewDetailsButtonActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void fsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");

                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"error in connection");
        }
    }//GEN-LAST:event_fsButtonActionPerformed

    private void lsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product where quantity <= 5;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");
                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_lsButtonActionPerformed

    private void changePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassButtonActionPerformed
        // TODO add your handling code here:
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(changePassPanel);
        subPanels.repaint();
        subPanels.revalidate();
    }//GEN-LAST:event_changePassButtonActionPerformed

    private void viewPurcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPurcButtonActionPerformed
        // TODO add your handling code here:
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(viewPurcPanel);
        subPanels.repaint();
        subPanels.revalidate();
    }//GEN-LAST:event_viewPurcButtonActionPerformed

    private void viewSaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSaleButtonActionPerformed
        // TODO add your handling code here:
        subPanels.removeAll();
        subPanels.repaint();
        subPanels.revalidate();
        //adding related panel
        subPanels.add(viewSalePanel);
        subPanels.repaint();
        subPanels.revalidate();
    }//GEN-LAST:event_viewSaleButtonActionPerformed

    private void selfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selfButtonActionPerformed
        // TODO add your handling code here:
        String oldpass = oldPasswordField.getText();
        String newpass = newPasswordField.getText();
        String confpass = confPasswordField.getText();
        boolean isNewMatch = false;
        if(newpass.equals(confpass))
        {
            isNewMatch = true;
            try
            {
                Class.forName("java.sql.Driver");
                Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
                Statement st= conn.createStatement();
                String qry = "select password from user where type = 'Owner' ;";
                ResultSet rs = st.executeQuery(qry);
                rs.next();
                String pass = rs.getString("password");
                if(isNewMatch)
                {
                    if(oldpass.equals(pass))
                    {
                        Statement st1= conn.createStatement();
                        String qry1 = "update user set password = '"+newpass+"' where type = 'Owner' ;";
                        st1.executeUpdate(qry1);
                        st1.close();
                        JOptionPane.showMessageDialog(this,"Password reset successfully");
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Invalid Old Password");
                    }
                }
                rs.close();
                st.close();
                conn.close();
                //JOptionPane.showMessageDialog(this,"Password reset successfully");

            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,e.getMessage());
                e.getStackTrace();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Password Does not Match.\n! Enter New Password Again");
        }
    }//GEN-LAST:event_selfButtonActionPerformed

    private void spButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spButtonActionPerformed
        // TODO add your handling code here:
        String oldpass = oldPasswordField.getText();
        String newpass = newPasswordField.getText();
        String confpass = confPasswordField.getText();
        boolean isNewMatch = false;
        if(newpass.equals(confpass))
        {
            isNewMatch = true;
            try
            {
                Class.forName("java.sql.Driver");
                Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
                Statement st= conn.createStatement();
                String qry = "select password from user where type = 'Sales Person' ;";
                ResultSet rs = st.executeQuery(qry);
                rs.next();
                String pass = rs.getString("password");
                if(isNewMatch)
                {
                    if(oldpass.equals(pass))
                    {
                        Statement st1= conn.createStatement();
                        String qry1 = "update user set password = '"+newpass+"' where type = 'Sales Person' ;";
                        st1.executeUpdate(qry1);
                        st1.close();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Invalid Old Password");
                    }
                }
                rs.close();
                st.close();
                conn.close();
                JOptionPane.showMessageDialog(this,"Password reset successfully");

            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(this,"error in connection");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Password Does not Match.\n! Enter New Password Again");
        }
    }//GEN-LAST:event_spButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OwnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OwnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OwnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OwnerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OwnerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanels;
    private javax.swing.JButton changePassButton;
    private javax.swing.JPanel changePassPanel;
    private javax.swing.JPasswordField confPasswordField;
    private javax.swing.JButton fsButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton logButton;
    private javax.swing.JButton lsButton;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField newPasswordField;
    private javax.swing.JPasswordField oldPasswordField;
    private javax.swing.JTable pTable;
    private javax.swing.JTextField passTF;
    private javax.swing.JLabel pfromLabel;
    private javax.swing.JTextField pfromdateTF;
    private javax.swing.JButton profButton;
    private javax.swing.JPanel profPanel;
    private javax.swing.JButton psearchButton;
    private javax.swing.JLabel ptoLabel;
    private javax.swing.JTextField ptodateTF;
    private javax.swing.JLabel ptransLabel;
    private javax.swing.JTable ptransTable;
    private javax.swing.JButton pviewAllButton;
    private javax.swing.JButton pviewDetailsButton;
    private javax.swing.JPanel roughPanel;
    private javax.swing.JButton selfButton;
    private javax.swing.JLabel sfromLabel;
    private javax.swing.JTextField sfromdateTF;
    private javax.swing.JButton smButton;
    private javax.swing.JButton spButton;
    private javax.swing.JButton ssearchButton;
    private javax.swing.JLabel stoLabel;
    private javax.swing.JButton stocButton;
    private javax.swing.JPanel stocPanel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JTextField stodateTF;
    private javax.swing.JLabel stransLabel;
    private javax.swing.JTable stransTable;
    private javax.swing.JPanel subPanels;
    private javax.swing.JButton suppButton;
    private javax.swing.JPanel suppPanel;
    private javax.swing.JTable suppTable;
    private javax.swing.JButton sviewAllButton;
    private javax.swing.JButton sviewDetailsButton;
    private javax.swing.JButton viewPurcButton;
    private javax.swing.JPanel viewPurcPanel;
    private javax.swing.JButton viewSaleButton;
    private javax.swing.JPanel viewSalePanel;
    // End of variables declaration//GEN-END:variables
    private void close()
    {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}
