/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

/**
 *
 * @author Deepak
 */
import java.sql.*;
import java.text.*;
import java.awt.print.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class SalesPersonForm extends javax.swing.JFrame {

    /**
     * Creates new form SalesPersonForm
     */
    float Total = 0;
    public SalesPersonForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        profButton = new javax.swing.JButton();
        stocButton = new javax.swing.JButton();
        salButton = new javax.swing.JButton();
        tranButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        roughPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        profPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        passTF = new javax.swing.JTextField();
        stockPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        fsButton = new javax.swing.JButton();
        lsButton = new javax.swing.JButton();
        tranPanel = new javax.swing.JPanel();
        stransLabel = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        stransTable = new javax.swing.JTable();
        sfromdateTF = new javax.swing.JTextField();
        sfromLabel = new javax.swing.JLabel();
        stoLabel = new javax.swing.JLabel();
        stodateTF = new javax.swing.JTextField();
        ssearchButton = new javax.swing.JButton();
        sviewAllButton = new javax.swing.JButton();
        sviewDetailsButton = new javax.swing.JButton();
        stPrintButton = new javax.swing.JButton();
        salPanel = new javax.swing.JPanel();
        StockPurchaseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tidTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        addNewSalPanel = new javax.swing.JPanel();
        pnameLabel = new javax.swing.JLabel();
        pnameTF = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        qtyTF = new javax.swing.JTextField();
        pidLabel = new javax.swing.JLabel();
        pidTF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        newProdTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        totalTF = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        paymentTF = new javax.swing.JTextField();
        Change = new javax.swing.JLabel();
        changeTF = new javax.swing.JTextField();
        setTotalButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(770, 540));
        setPreferredSize(new java.awt.Dimension(770, 540));

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 540));
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 540));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("**********Sales Person**********");

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));

        profButton.setBackground(new java.awt.Color(255, 153, 51));
        profButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        profButton.setText("Profile");
        profButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profButton.setMaximumSize(new java.awt.Dimension(100, 100));
        profButton.setMinimumSize(new java.awt.Dimension(100, 100));
        profButton.setPreferredSize(new java.awt.Dimension(100, 100));
        profButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profButtonActionPerformed(evt);
            }
        });

        stocButton.setBackground(new java.awt.Color(255, 153, 51));
        stocButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        stocButton.setText("Stock");
        stocButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stocButton.setMaximumSize(new java.awt.Dimension(100, 100));
        stocButton.setMinimumSize(new java.awt.Dimension(100, 100));
        stocButton.setPreferredSize(new java.awt.Dimension(100, 100));
        stocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocButtonActionPerformed(evt);
            }
        });

        salButton.setBackground(new java.awt.Color(255, 153, 51));
        salButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        salButton.setText("Sale");
        salButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        salButton.setMaximumSize(new java.awt.Dimension(100, 100));
        salButton.setMinimumSize(new java.awt.Dimension(100, 100));
        salButton.setPreferredSize(new java.awt.Dimension(100, 100));
        salButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salButtonActionPerformed(evt);
            }
        });

        tranButton.setBackground(new java.awt.Color(255, 153, 51));
        tranButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        tranButton.setText("Transactions");
        tranButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tranButton.setMaximumSize(new java.awt.Dimension(100, 100));
        tranButton.setMinimumSize(new java.awt.Dimension(100, 100));
        tranButton.setPreferredSize(new java.awt.Dimension(100, 100));
        tranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranButtonActionPerformed(evt);
            }
        });

        logButton.setBackground(new java.awt.Color(255, 153, 51));
        logButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        logButton.setText("logout");
        logButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logButton.setMaximumSize(new java.awt.Dimension(100, 100));
        logButton.setMinimumSize(new java.awt.Dimension(100, 100));
        logButton.setPreferredSize(new java.awt.Dimension(100, 100));
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(tranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stocButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(profButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(salButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jPanel3.setLayout(new java.awt.CardLayout());

        roughPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel2.setFont(new java.awt.Font("Vivaldi", 1, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Welcome");

        javax.swing.GroupLayout roughPanelLayout = new javax.swing.GroupLayout(roughPanel);
        roughPanel.setLayout(roughPanelLayout);
        roughPanelLayout.setHorizontalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roughPanelLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        roughPanelLayout.setVerticalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roughPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel3.add(roughPanel, "card2");

        profPanel.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("ID");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 51));
        jLabel6.setText("Password");

        javax.swing.GroupLayout profPanelLayout = new javax.swing.GroupLayout(profPanel);
        profPanel.setLayout(profPanelLayout);
        profPanelLayout.setHorizontalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profPanelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(profPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passTF))
                    .addGroup(profPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idTF))
                    .addGroup(profPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(187, 187, 187))
        );
        profPanelLayout.setVerticalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPanelLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jPanel3.add(profPanel, "card3");

        stockPanel.setBackground(new java.awt.Color(153, 0, 0));

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Type", "Buying Price", "Selling Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(pTable);

        fsButton.setText("View Full Stock");
        fsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsButtonActionPerformed(evt);
            }
        });

        lsButton.setText("Least Stock");
        lsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stockPanelLayout = new javax.swing.GroupLayout(stockPanel);
        stockPanel.setLayout(stockPanelLayout);
        stockPanelLayout.setHorizontalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(fsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(stockPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        stockPanelLayout.setVerticalGroup(
            stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(stockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lsButton)
                    .addComponent(fsButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jPanel3.add(stockPanel, "card4");

        tranPanel.setBackground(new java.awt.Color(153, 0, 0));

        stransLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        stransLabel.setForeground(new java.awt.Color(255, 102, 0));
        stransLabel.setText("Sale Transactions");

        stransTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "transaction ID", "Puchase Date", "Total Cost"
            }
        ));
        jScrollPane5.setViewportView(stransTable);

        sfromdateTF.setText("yyyy-mm-dd");

        sfromLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sfromLabel.setForeground(new java.awt.Color(255, 102, 0));
        sfromLabel.setText("From");

        stoLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        stoLabel.setForeground(new java.awt.Color(255, 102, 0));
        stoLabel.setText("To");

        stodateTF.setText("yyyy-mm-dd");
        stodateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stodateTFActionPerformed(evt);
            }
        });

        ssearchButton.setText("search");
        ssearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssearchButtonActionPerformed(evt);
            }
        });

        sviewAllButton.setText("View All");
        sviewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sviewAllButtonActionPerformed(evt);
            }
        });

        sviewDetailsButton.setText("View Details");
        sviewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sviewDetailsButtonActionPerformed(evt);
            }
        });

        stPrintButton.setText("Print");
        stPrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stPrintButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tranPanelLayout = new javax.swing.GroupLayout(tranPanel);
        tranPanel.setLayout(tranPanelLayout);
        tranPanelLayout.setHorizontalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tranPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tranPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stransLabel)
                            .addGroup(tranPanelLayout.createSequentialGroup()
                                .addComponent(sfromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(stoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ssearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addComponent(sviewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tranPanelLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(sviewDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119)
                        .addComponent(stPrintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        tranPanelLayout.setVerticalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(stransLabel)
                .addGap(18, 18, 18)
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sfromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfromLabel)
                    .addComponent(stoLabel)
                    .addComponent(stodateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssearchButton)
                    .addComponent(sviewAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sviewDetailsButton)
                    .addComponent(stPrintButton))
                .addGap(28, 28, 28))
        );

        jPanel3.add(tranPanel, "card7");

        StockPurchaseLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        StockPurchaseLabel.setText("New Sale");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Transaction ID");

        pnameLabel.setText("Product name");

        qtyLabel.setText("Quantity");

        pidLabel.setText("Product ID");

        newProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Quantity", "Selling Price", "Net Cost"
            }
        ));
        jScrollPane3.setViewportView(newProdTable);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        totalTF.setText("0");

        totalLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        totalLabel.setText("Total");

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Payment");

        paymentTF.setText("0");

        Change.setText("Change");

        changeTF.setText("0");

        setTotalButton.setText("Set Total");
        setTotalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setTotalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewSalPanelLayout = new javax.swing.GroupLayout(addNewSalPanel);
        addNewSalPanel.setLayout(addNewSalPanelLayout);
        addNewSalPanelLayout.setHorizontalGroup(
            addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewSalPanelLayout.createSequentialGroup()
                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addNewSalPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewSalPanelLayout.createSequentialGroup()
                                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Change)
                                    .addComponent(jLabel5))
                                .addGap(36, 36, 36)
                                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(paymentTF, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(changeTF)))
                            .addGroup(addNewSalPanelLayout.createSequentialGroup()
                                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewSalPanelLayout.createSequentialGroup()
                                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pnameLabel)
                                            .addComponent(pidLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(addNewSalPanelLayout.createSequentialGroup()
                                        .addComponent(qtyLabel)
                                        .addGap(34, 34, 34)))
                                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(qtyTF, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(pnameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pidTF, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(16, 16, 16))
                    .addGroup(addNewSalPanelLayout.createSequentialGroup()
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addNewSalPanelLayout.createSequentialGroup()
                                .addComponent(finishButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(addNewSalPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(setTotalButton)
                        .addGap(18, 18, 18)
                        .addComponent(totalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12))
        );
        addNewSalPanelLayout.setVerticalGroup(
            addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewSalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addNewSalPanelLayout.createSequentialGroup()
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pidLabel))
                        .addGap(18, 18, 18)
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(qtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyLabel))
                        .addGap(19, 19, 19)
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(paymentTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Change)
                            .addComponent(changeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(addNewSalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(finishButton)
                    .addComponent(printButton)
                    .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel)
                    .addComponent(setTotalButton))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(addNewSalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addNewSalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout salPanelLayout = new javax.swing.GroupLayout(salPanel);
        salPanel.setLayout(salPanelLayout);
        salPanelLayout.setHorizontalGroup(
            salPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, salPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StockPurchaseLabel)
                .addGap(281, 281, 281))
            .addGroup(salPanelLayout.createSequentialGroup()
                .addGroup(salPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(salPanelLayout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel7)
                        .addGap(55, 55, 55)
                        .addComponent(tidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(salPanelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salPanelLayout.setVerticalGroup(
            salPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StockPurchaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(salPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(salPanel, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(186, 186, 186))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(profPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        addProfFields();
    }//GEN-LAST:event_profButtonActionPerformed
    public void addProfFields()
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= con.createStatement();
            String qry = "select * from user where type = 'Sales Person';";
            ResultSet rs = st.executeQuery(qry);
            rs.next();
            String uid=rs.getString("uID"); 
            String uname=rs.getString("uname");
            String pass=rs.getString("password");
            nameTF.setText(uname);
            idTF.setText(uid);
            passTF.setText(pass);
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    private void stocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(stockPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_stocButtonActionPerformed

    private void salButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(salPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        //String tid = Integer.toString(newTransactionID());
        tidTF.setText(Integer.toString(newTransactionID()));

    }//GEN-LAST:event_salButtonActionPerformed
    public int newTransactionID()
    {   
        int stid = 0;
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select stID from sale_order;";
            ResultSet rs = st.executeQuery(qry);
            
            if(!rs.next())
            {
                stid=1;
                
            }
            else
            {
                while(!rs.last())
                {
                    rs.next();
                }
                stid=rs.getInt("stID");
                rs.close();
                st.close();
                conn.close();
                ++stid;
            }
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.getStackTrace();
        }
        return stid;
    }
    private void tranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(tranPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_tranButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            this.close();
            login log = new login();
            log.setVisible(true);

        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Login foem can't be opened.");
        }
    }//GEN-LAST:event_logButtonActionPerformed

    private void fsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");

                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"error in connection");
        }
    }//GEN-LAST:event_fsButtonActionPerformed

    private void lsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product where quantity <= 5;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");
                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_lsButtonActionPerformed

    private void stodateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stodateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stodateTFActionPerformed

    private void ssearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssearchButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) stransTable.getModel();
        String from = sfromdateTF.getText();
        String to = stodateTF.getText();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from sale_order where sale_date between "+
                    "'"+from+"' and "+"'"+to+"' order by sale_date asc;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty = false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("stID");
                String date = rs.getString("sale_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in ssearchButtonActionPerformed");
            e.printStackTrace();
        }
    }//GEN-LAST:event_ssearchButtonActionPerformed

    private void sviewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sviewAllButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) stransTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from sale_order order by stID;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("stID");
                String date = rs.getString("sale_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        }
    }//GEN-LAST:event_sviewAllButtonActionPerformed

    private void sviewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sviewDetailsButtonActionPerformed
        // TODO add your handling code here:
        viewSTransactionDetails1 std = new viewSTransactionDetails1();
        std.setVisible(true);
    }//GEN-LAST:event_sviewDetailsButtonActionPerformed
    public String[] getProdFields()
    {
        String str[] = new String[6];
        str[0]= pidTF.getText();
        str[1]= pnameTF.getText();
        str[2]= qtyTF.getText();
        return str;
    }
    public void updateS_O_DBtable(int stid, float tcost)
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            
            if(tcost==0)
            {
                String qry = "insert into sale_order (stID,sale_date,total_cost) values(?,?,?)";
                PreparedStatement pst = conn.prepareStatement(qry);
                pst.setInt(1, stid);
                java.sql.Date  sqlDate = new java.sql.Date(new java.util.Date().getTime());
                pst.setDate(2, sqlDate);
                pst.setFloat(3, 0);
                pst.executeUpdate();
                pst.close();
            }
            else
            {
                String qry = "update sale_order set total_cost ="+tcost+"where stID ="+stid+";";
                Statement st = conn.createStatement();
                int i = st.executeUpdate(qry);
                if(i!=0)
                    JOptionPane.showMessageDialog(this,"Total cost updated.");
                else
                    JOptionPane.showMessageDialog(this,"Total cost is not updated.");
                st.close();
            }
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in updateP_O_DBtable");
            e.printStackTrace();
        }
    }
    public void updateS_O_SDBtable(int pid, int qty, float ncost)
    {
        try
        { 
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            //checking and updating sale_order in DB.
            int tid=Integer.parseInt(tidTF.getText());
            int t=0;
            String qry2 = "select stID from sale_order;";
            Statement st2 = conn.createStatement();
            ResultSet rs2 = st2.executeQuery(qry2);
            boolean flag=false;
            while(rs2.next())
            {
                if(tid==rs2.getInt("stID"))
                {    
                    t=rs2.getInt("stID");
                    flag=true;
                }
            }
            st2.close();
            rs2.close();
            if(flag==false)
            {  
                updateS_O_DBtable(tid,0);
            }
            //updating sale table 
            String qry1 = "insert into sale(pID,stID,quantity,net_cost) "
                                        + "values(?, ?, ?, ?)";
            PreparedStatement pst1 = conn.prepareStatement(qry1);
            pst1.setInt(1, pid);
            pst1.setInt(2, tid);
            pst1.setInt(3, qty);
            pst1.setFloat(4, ncost);
            pst1.executeUpdate();
            pst1.close();
            
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in updateS_O_SDBtable");
            e.printStackTrace();
        }
    }
    public void updateP_qty(int pid,int qt)
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "update product set quantity = "+qt+" where pID = "+pid+" ;";
            st.executeUpdate(qry);
            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in updateP_qty");
            e.printStackTrace();
        }
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        String pfields[];
        pfields = getProdFields();
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select pID,pname,quantity,selling_price from product where pID = "+pfields[0]+";";
            ResultSet rs = st.executeQuery(qry);
            if(!rs.next())
                 JOptionPane.showMessageDialog(this,"Item Not found with his id");
            else
            {
                int pid = rs.getInt("pID");
                String name = rs.getString("pname");
                int qty = rs.getInt("quantity");
                float sp = rs.getFloat("selling_price");
                float nc = sp*Integer.parseInt(pfields[2]);
                Total=Total+nc;
                int qt = qty-Integer.parseInt(pfields[2]);
                model.addRow(new Object[]{name,Integer.parseInt(pfields[2]),sp,nc});
                updateS_O_SDBtable(pid,Integer.parseInt(pfields[2]),nc);
                updateP_qty(pid,qt);
            }
            rs.close();
            st.close();
            conn.close();
            totalTF.setText(Float.toString(Total));
            resetNewProdTFs();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in nextButton");
            e.printStackTrace();
        }
    }//GEN-LAST:event_nextButtonActionPerformed
    public void resetNewProdTFs()
    {
        pidTF.setText("");
        pnameTF.setText("");
        qtyTF.setText("");
        paymentTF.setText("");
        changeTF.setText("");
    }
    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        float total = Float.parseFloat(totalTF.getText());
        int tID = Integer.parseInt(tidTF.getText());
        updateS_O_DBtable(tID,total);
        //opening profile panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        
        //adding related panel
        jPanel3.add(roughPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        model.setRowCount(0);
        totalTF.setText("0.0");
        Total=0;
    }//GEN-LAST:event_finishButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        
        MessageFormat header = new MessageFormat("Sale No: "+tidTF.getText());
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            newProdTable.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("cant print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void stPrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stPrintButtonActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            stransTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("cant print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_stPrintButtonActionPerformed

    private void setTotalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setTotalButtonActionPerformed
        // TODO add your handling code here:
        setChange();
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        model.addRow(new Object[]{"---------","---------","---------","---------"});
        model.addRow(new Object[]{"---------","---------","Total",totalTF.getText()});
        model.addRow(new Object[]{"---------","---------","Payment",paymentTF.getText()});
        model.addRow(new Object[]{"---------","---------","Change",changeTF.getText()});
    }//GEN-LAST:event_setTotalButtonActionPerformed
    public void setChange()
    {
        float total = Float.parseFloat(totalTF.getText());
        float payment = Float.parseFloat(paymentTF.getText());
        String st;
        changeTF.setText(Float.toString(payment-total));
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesPersonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesPersonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesPersonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesPersonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesPersonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Change;
    private javax.swing.JLabel StockPurchaseLabel;
    private javax.swing.JPanel addNewSalPanel;
    private javax.swing.JTextField changeTF;
    private javax.swing.JButton finishButton;
    private javax.swing.JButton fsButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton logButton;
    private javax.swing.JButton lsButton;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTable newProdTable;
    private javax.swing.JButton nextButton;
    private javax.swing.JTable pTable;
    private javax.swing.JTextField passTF;
    private javax.swing.JTextField paymentTF;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextField pidTF;
    private javax.swing.JLabel pnameLabel;
    private javax.swing.JTextField pnameTF;
    private javax.swing.JButton printButton;
    private javax.swing.JButton profButton;
    private javax.swing.JPanel profPanel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyTF;
    private javax.swing.JPanel roughPanel;
    private javax.swing.JButton salButton;
    private javax.swing.JPanel salPanel;
    private javax.swing.JButton setTotalButton;
    private javax.swing.JLabel sfromLabel;
    private javax.swing.JTextField sfromdateTF;
    private javax.swing.JButton ssearchButton;
    private javax.swing.JButton stPrintButton;
    private javax.swing.JLabel stoLabel;
    private javax.swing.JButton stocButton;
    private javax.swing.JPanel stockPanel;
    private javax.swing.JTextField stodateTF;
    private javax.swing.JLabel stransLabel;
    private javax.swing.JTable stransTable;
    private javax.swing.JButton sviewAllButton;
    private javax.swing.JButton sviewDetailsButton;
    private javax.swing.JTextField tidTF;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTF;
    private javax.swing.JButton tranButton;
    private javax.swing.JPanel tranPanel;
    // End of variables declaration//GEN-END:variables
 private void close()
    {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
}

