/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package loginform;

import java.sql.*;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Deepak
 */
public class StockManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form StockManagerForm
     */
    public StockManagerForm() 
    {
        initComponents();
        
        Toolkit tool = Toolkit.getDefaultToolkit();
        Dimension dim = new Dimension(tool.getScreenSize());
        int height = (int) dim.getHeight();
        int width = (int) dim.getWidth();
        setSize(height,width);
        setLocation(width/2 - getWidth()/2, height/2 - getHeight()/2);
        this.setResizable(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        profButton = new javax.swing.JButton();
        stocButton = new javax.swing.JButton();
        suppButton = new javax.swing.JButton();
        PurcButton = new javax.swing.JButton();
        tranButton = new javax.swing.JButton();
        logButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        roughPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        profPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        idTF = new javax.swing.JTextField();
        passTF = new javax.swing.JTextField();
        stocPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pTable = new javax.swing.JTable();
        fsButton = new javax.swing.JButton();
        lsButton = new javax.swing.JButton();
        suppPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        suppTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        addSuppButton = new javax.swing.JButton();
        purcPanel = new javax.swing.JPanel();
        StockPurchaseLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tidTF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        blankPanel = new javax.swing.JPanel();
        addNewProPanel = new javax.swing.JPanel();
        addSuppIDLable = new javax.swing.JLabel();
        addSuppIDTF = new javax.swing.JTextField();
        pnameLabel = new javax.swing.JLabel();
        pnameTF = new javax.swing.JTextField();
        ptypeLabel = new javax.swing.JLabel();
        ptypeTF = new javax.swing.JTextField();
        upriceLabel = new javax.swing.JLabel();
        upriceTF = new javax.swing.JTextField();
        qtyLabel = new javax.swing.JLabel();
        qtyTF = new javax.swing.JTextField();
        pidLabel = new javax.swing.JLabel();
        pidTF = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        newProdTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        finishButton = new javax.swing.JButton();
        totalTF = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();
        printButton = new javax.swing.JButton();
        addNewProButton = new javax.swing.JButton();
        tranPanel = new javax.swing.JPanel();
        transLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        transTable = new javax.swing.JTable();
        fromdateTF = new javax.swing.JTextField();
        fromLabel = new javax.swing.JLabel();
        toLabel = new javax.swing.JLabel();
        todateTF = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        viewAllButton = new javax.swing.JButton();
        viewDetailsButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(843, 870));
        addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                formComponentAdded(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));

        profButton.setBackground(new java.awt.Color(255, 153, 51));
        profButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        profButton.setText("Profile");
        profButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        profButton.setMaximumSize(new java.awt.Dimension(100, 100));
        profButton.setMinimumSize(new java.awt.Dimension(100, 100));
        profButton.setPreferredSize(new java.awt.Dimension(100, 100));
        profButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profButtonActionPerformed(evt);
            }
        });

        stocButton.setBackground(new java.awt.Color(255, 153, 51));
        stocButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        stocButton.setText("Stock");
        stocButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        stocButton.setMaximumSize(new java.awt.Dimension(100, 100));
        stocButton.setMinimumSize(new java.awt.Dimension(100, 100));
        stocButton.setPreferredSize(new java.awt.Dimension(100, 100));
        stocButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocButtonActionPerformed(evt);
            }
        });

        suppButton.setBackground(new java.awt.Color(255, 153, 51));
        suppButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        suppButton.setText("Supplier");
        suppButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        suppButton.setMaximumSize(new java.awt.Dimension(100, 100));
        suppButton.setMinimumSize(new java.awt.Dimension(100, 100));
        suppButton.setPreferredSize(new java.awt.Dimension(100, 100));
        suppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppButtonActionPerformed(evt);
            }
        });

        PurcButton.setBackground(new java.awt.Color(255, 153, 51));
        PurcButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        PurcButton.setText("Purchase");
        PurcButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PurcButton.setMaximumSize(new java.awt.Dimension(100, 100));
        PurcButton.setMinimumSize(new java.awt.Dimension(100, 100));
        PurcButton.setPreferredSize(new java.awt.Dimension(100, 100));
        PurcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurcButtonActionPerformed(evt);
            }
        });

        tranButton.setBackground(new java.awt.Color(255, 153, 51));
        tranButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        tranButton.setText("Transactions");
        tranButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tranButton.setMaximumSize(new java.awt.Dimension(100, 100));
        tranButton.setMinimumSize(new java.awt.Dimension(100, 100));
        tranButton.setPreferredSize(new java.awt.Dimension(100, 100));
        tranButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tranButtonActionPerformed(evt);
            }
        });

        logButton.setBackground(new java.awt.Color(255, 153, 51));
        logButton.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 18)); // NOI18N
        logButton.setText("logout");
        logButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        logButton.setMaximumSize(new java.awt.Dimension(100, 100));
        logButton.setMinimumSize(new java.awt.Dimension(100, 100));
        logButton.setPreferredSize(new java.awt.Dimension(100, 100));
        logButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(tranButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PurcButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stocButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(profButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stocButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(suppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PurcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tranButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange, java.awt.Color.orange));
        jPanel3.setLayout(new java.awt.CardLayout());

        roughPanel.setBackground(new java.awt.Color(153, 0, 0));
        roughPanel.setPreferredSize(new java.awt.Dimension(593, 478));

        jLabel6.setFont(new java.awt.Font("Vivaldi", 1, 65)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("Welcome");

        javax.swing.GroupLayout roughPanelLayout = new javax.swing.GroupLayout(roughPanel);
        roughPanel.setLayout(roughPanelLayout);
        roughPanelLayout.setHorizontalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roughPanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        roughPanelLayout.setVerticalGroup(
            roughPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roughPanelLayout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jPanel3.add(roughPanel, "card2");

        profPanel.setBackground(new java.awt.Color(153, 0, 0));
        profPanel.setPreferredSize(new java.awt.Dimension(593, 478));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Name");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 51));
        jLabel4.setText("ID");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 51));
        jLabel5.setText("Password");

        idTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profPanelLayout = new javax.swing.GroupLayout(profPanel);
        profPanel.setLayout(profPanelLayout);
        profPanelLayout.setHorizontalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        profPanelLayout.setVerticalGroup(
            profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profPanelLayout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nameTF))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
        );

        jPanel3.add(profPanel, "card2");

        stocPanel.setBackground(new java.awt.Color(153, 0, 0));
        stocPanel.setPreferredSize(new java.awt.Dimension(593, 478));

        pTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product name", "Type", "Buying Price", "Selling Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(pTable);

        fsButton.setText("View Full Stock");
        fsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsButtonActionPerformed(evt);
            }
        });

        lsButton.setText("Least Stock");
        lsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stocPanelLayout = new javax.swing.GroupLayout(stocPanel);
        stocPanel.setLayout(stocPanelLayout);
        stocPanelLayout.setHorizontalGroup(
            stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(stocPanelLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(fsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(lsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        stocPanelLayout.setVerticalGroup(
            stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stocPanelLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(stocPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fsButton)
                    .addComponent(lsButton))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.add(stocPanel, "card2");

        suppPanel.setBackground(new java.awt.Color(153, 0, 0));
        suppPanel.setPreferredSize(new java.awt.Dimension(593, 478));

        suppTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier name", "Address", "Phone no#", "City", "Country", "Email ID"
            }
        ));
        jScrollPane2.setViewportView(suppTable);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("**********Suppliers**********");

        addSuppButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addSuppButton.setText("Add Supplier");
        addSuppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSuppButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suppPanelLayout = new javax.swing.GroupLayout(suppPanel);
        suppPanel.setLayout(suppPanelLayout);
        suppPanelLayout.setHorizontalGroup(
            suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suppPanelLayout.createSequentialGroup()
                .addGroup(suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suppPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(suppPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)
                        .addGap(0, 111, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(suppPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(addSuppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        suppPanelLayout.setVerticalGroup(
            suppPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, suppPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSuppButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jPanel3.add(suppPanel, "card2");

        purcPanel.setPreferredSize(new java.awt.Dimension(597, 494));

        StockPurchaseLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        StockPurchaseLabel.setText("Stock Purchase");

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel7.setText("Transaction ID");

        javax.swing.GroupLayout blankPanelLayout = new javax.swing.GroupLayout(blankPanel);
        blankPanel.setLayout(blankPanelLayout);
        blankPanelLayout.setHorizontalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        blankPanelLayout.setVerticalGroup(
            blankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        addSuppIDLable.setText("Add Supplier ID");

        pnameLabel.setText("Product name");

        ptypeLabel.setText("Product type");

        ptypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptypeTFActionPerformed(evt);
            }
        });

        upriceLabel.setText("Unit Price");

        upriceTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upriceTFActionPerformed(evt);
            }
        });

        qtyLabel.setText("Quantity");

        pidLabel.setText("Product ID");

        newProdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product name", "Quantity", "Unit Price", "Net Cost"
            }
        ));
        jScrollPane3.setViewportView(newProdTable);

        nextButton.setText("Next");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        finishButton.setText("Finish");
        finishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishButtonActionPerformed(evt);
            }
        });

        totalTF.setText("0");

        totalLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        totalLabel.setText("Total");

        printButton.setText("Print");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addNewProPanelLayout = new javax.swing.GroupLayout(addNewProPanel);
        addNewProPanel.setLayout(addNewProPanelLayout);
        addNewProPanelLayout.setHorizontalGroup(
            addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewProPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(addNewProPanelLayout.createSequentialGroup()
                        .addComponent(addSuppIDLable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addSuppIDTF, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(addNewProPanelLayout.createSequentialGroup()
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(upriceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ptypeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .addComponent(qtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upriceTF)
                            .addComponent(ptypeTF)
                            .addComponent(qtyTF)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewProPanelLayout.createSequentialGroup()
                        .addComponent(nextButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(printButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(finishButton))
                    .addGroup(addNewProPanelLayout.createSequentialGroup()
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pidTF)
                            .addComponent(pnameTF))))
                .addGap(18, 18, 18)
                .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addNewProPanelLayout.createSequentialGroup()
                        .addGap(0, 112, Short.MAX_VALUE)
                        .addComponent(totalLabel)
                        .addGap(27, 27, 27)
                        .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        addNewProPanelLayout.setVerticalGroup(
            addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addNewProPanelLayout.createSequentialGroup()
                .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addNewProPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSuppIDLable)
                            .addComponent(addSuppIDTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pidLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(addNewProPanelLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(pnameLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ptypeLabel)
                            .addComponent(ptypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upriceLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtyTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qtyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nextButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(printButton))))
                    .addGroup(addNewProPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addNewProPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalLabel))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNewProPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addNewProPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(blankPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        addNewProButton.setText("Add new product");
        addNewProButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewProButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout purcPanelLayout = new javax.swing.GroupLayout(purcPanel);
        purcPanel.setLayout(purcPanelLayout);
        purcPanelLayout.setHorizontalGroup(
            purcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, purcPanelLayout.createSequentialGroup()
                .addGroup(purcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(purcPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(StockPurchaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(purcPanelLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(tidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(152, 152, 152))
            .addGroup(purcPanelLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(addNewProButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        purcPanelLayout.setVerticalGroup(
            purcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(purcPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(StockPurchaseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(purcPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tidTF, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(addNewProButton)
                .addGap(31, 31, 31)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(purcPanel, "card2");

        transLabel.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        transLabel.setText("Transactions");

        transTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Puchase Date", "Total Cast"
            }
        ));
        jScrollPane4.setViewportView(transTable);

        fromdateTF.setText("yyyy-mm-dd");

        fromLabel.setText("From");

        toLabel.setText("To");

        todateTF.setText("yyyy-mm-dd");
        todateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todateTFActionPerformed(evt);
            }
        });

        searchButton.setText("search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        viewAllButton.setText("View All");
        viewAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllButtonActionPerformed(evt);
            }
        });

        viewDetailsButton.setText("View Details");
        viewDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tranPanelLayout = new javax.swing.GroupLayout(tranPanel);
        tranPanel.setLayout(tranPanelLayout);
        tranPanelLayout.setHorizontalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tranPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4))
                    .addGroup(tranPanelLayout.createSequentialGroup()
                        .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tranPanelLayout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(transLabel))
                            .addGroup(tranPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(fromLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(todateTF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(viewAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tranPanelLayout.createSequentialGroup()
                                .addGap(272, 272, 272)
                                .addComponent(viewDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 68, Short.MAX_VALUE)))
                .addContainerGap())
        );
        tranPanelLayout.setVerticalGroup(
            tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tranPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transLabel)
                .addGap(20, 20, 20)
                .addGroup(tranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromdateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromLabel)
                    .addComponent(toLabel)
                    .addComponent(todateTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(viewAllButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewDetailsButton)
                .addGap(28, 28, 28))
        );

        jPanel3.add(tranPanel, "card2");

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("**********Stock Manager**********");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    float Total = 0;
    private void formComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_formComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentAdded

    private void profButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(profPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        addProfFields();
    }//GEN-LAST:event_profButtonActionPerformed
    public void addProfFields()
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= con.createStatement();
            String qry = "select * from user where type = 'Stock Manager'";
            ResultSet rs = st.executeQuery(qry);
            rs.next();
            String uid=rs.getString("uID"); 
            String uname=rs.getString("uname");
            String pass=rs.getString("password");
            nameTF.setText(uname);
            idTF.setText(uid);
            passTF.setText(pass);
            
          
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }
    private void stocButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(stocPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        
    }//GEN-LAST:event_stocButtonActionPerformed

    private void suppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(suppPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        fillSuppTable();
    }//GEN-LAST:event_suppButtonActionPerformed
    public void fillSuppTable()
    {
        DefaultTableModel model = (DefaultTableModel) suppTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from supplier;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String sid=rs.getString("sID");
                String sname=rs.getString("sname");
                String address=rs.getString("address");
                String phone=rs.getString("phone");
                String city=rs.getString("city");
                String country=rs.getString("country");
                String email=rs.getString("email");
                
                model.addRow(new Object[]{sid,sname,address,phone,city,country,email});
            }
            rs.close();
            st.close();
            conn.close();   
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"error in connection");
        }
    }
    private void PurcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurcButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(purcPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
               //String tid = Integer.toString(newTransactionID());
        tidTF.setText(Integer.toString(newTransactionID()));
            
       
        
    }//GEN-LAST:event_PurcButtonActionPerformed
    public int newTransactionID()
    {   
        int ptid = 0;
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select ptID from purchase_order;";
            ResultSet rs = st.executeQuery(qry);
            
            if(!rs.next())
            {
                ptid=1;
                
            }
            else
            {
                while(!rs.last())
                {
                    rs.next();
                }
                ptid=rs.getInt("ptID");
                rs.close();
                st.close();
                conn.close();
                ++ptid;
            }
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            e.getStackTrace();
        }
        return ptid;
    }
    private void tranButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tranButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(tranPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
    }//GEN-LAST:event_tranButtonActionPerformed

    private void logButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            this.close();
            login log = new login();
            log.setVisible(true);
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Login foem can't be opened.");
        }
    }//GEN-LAST:event_logButtonActionPerformed

    private void fsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");
                
                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
        rs.close();
        st.close();
        conn.close();   
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,"error in connection");
    }
    }//GEN-LAST:event_fsButtonActionPerformed

    private void lsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lsButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) pTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product where quantity <= 5;";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pid=rs.getString("pID");
                String pname=rs.getString("pname");
                String type=rs.getString("type");
                String up=rs.getString("unit_price");
                String sp=rs.getString("selling_price");
                String qty=rs.getString("quantity");
                model.addRow(new Object[]{pid,pname,type,up,sp,qty});
            }
            rs.close();
            st.close();
            conn.close();   
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(this,e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_lsButtonActionPerformed

    private void addSuppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuppButtonActionPerformed
        // TODO add your handling code here:
        SupplierForm sf = new SupplierForm();
        sf.setVisible(true);
    }//GEN-LAST:event_addSuppButtonActionPerformed

    private void ptypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptypeTFActionPerformed

    private void upriceTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upriceTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upriceTFActionPerformed

    private void todateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_todateTFActionPerformed

    private void addNewProButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewProButtonActionPerformed
        // TODO add your handling code here:
        //romoving panel
        jPanel4.removeAll();
        jPanel4.repaint();
        jPanel4.revalidate();
        //adding related panel
        jPanel4.add(addNewProPanel);
        jPanel4.repaint();
        jPanel4.revalidate();
        //updateP_O_DBtable(Integer.parseInt(tidTF.getText()),0);
        
    }//GEN-LAST:event_addNewProButtonActionPerformed

    public void update_tid_date()
    {
        String pfields[];
        pfields = getProdFields();
        int tid = newTransactionID();
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String qry1 = "select ptID from purchase_order;";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(qry1);
            if(!rs.next())
            {
                String qry = "insert into purchase_order(ptID,purchase_date,total_cost) "+ "values(?, ?, ?)";
                PreparedStatement pst = conn.prepareStatement(qry);
                pst.setInt(1, tid);
                java.sql.Date  sqlDate = new java.sql.Date(new java.util.Date().getTime());
                pst.setDate(2, sqlDate);
                pst.setInt(3, 0);
                pst.executeUpdate();
                pst.close();
                
            }
            else
            {
                rs.previous();
                boolean flag = false;
                while(rs.next())
                {
                    if(tid == rs.getInt("ptID"))
                    {
                        flag=true;
                        break;
                    }
                }
                if(flag==false)
                {
                    String qry = "insert into purchase_order(ptID,purchase_date,total_cost) "+ "values(?, ?, ?)";
                    PreparedStatement pst = conn.prepareStatement(qry);
                    pst.setInt(1, tid);
                    java.sql.Date  sqlDate = new java.sql.Date(new java.util.Date().getTime());
                    pst.setDate(2, sqlDate);
                    pst.setInt(3, 0);
                    pst.executeUpdate();
                    pst.close();
                }
            }
            rs.close();
            st.close();
            conn.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in update_tid_date");
            e.printStackTrace();
        }
    }
    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:
        String pfields[];
        pfields = getProdFields();
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select sID from supplier;";
            ResultSet rs = st.executeQuery(qry);
            int sid;
            if(!rs.next())
            {
               JOptionPane.showMessageDialog(this,"There is no supplier with id "+pfields[0]);
            }
            else
            {
                rs.previous();
                while(rs.next())
                {
                    sid=rs.getInt("sID");
                    if(sid == Integer.parseInt(pfields[0]))
                    {
                        Statement st1= conn.createStatement();
                        String qry1 = "select pID from product;";
                        ResultSet rs1 = st1.executeQuery(qry1);
                        int pid;
                        if(!rs1.next())
                        {
                            insertProduct();
                            float qty = Float.parseFloat(pfields[5]);
                            float up = Float.parseFloat(pfields[4]);
                            float nc = qty*up;
                            updateS_P_DBtable(sid,Integer.parseInt(pfields[1]),
                                    Integer.parseInt(pfields[5]),nc);
                        }
                        else
                        {
                            boolean flag = false;
                            rs1.previous();
                            while(rs1.next())
                            {
                                pid=rs1.getInt("pID");
                                if(pid == Integer.parseInt(pfields[1]))
                                {
                                    flag=true;
                                    Float up=Float.parseFloat(pfields[4]);
                                    int qt=Integer.parseInt(pfields[5]);
                                    Float sp = (float)(up+(up * 0.1));
                                    try
                                    {
                                        Statement st2= conn.createStatement();
                                        String qry2 = "update product set unit_price="+up+
                                                " ,quantity=quantity+"+qt+",selling_price= "+sp+
                                                " where pID = "+pid+";";
                                        int i=0; 
                                        i=st2.executeUpdate(qry2);
                                        if(i==1)
                                        {
                                            JOptionPane.showMessageDialog(this,"Product successfully updated.");
                                             float qty = Float.parseFloat(pfields[5]);
                                             float up1 = Float.parseFloat(pfields[4]);
                                             float nc = qty*up1;
                                             updateS_P_DBtable(sid,Integer.parseInt(pfields[1]),
                                             Integer.parseInt(pfields[5]),nc);  
                                        } 
                                        st2.close();
                                    }
                                    catch(Exception e)
                                    {
                                        JOptionPane.showMessageDialog(this,"product not updated.");
                                        e.printStackTrace();
                                    }
                                }    
                            }
                            if(!flag)
                            {
                                insertProduct();
                                float qty = Float.parseFloat(pfields[5]);
                                float up = Float.parseFloat(pfields[4]);
                                float nc = qty*up;
                                updateS_P_DBtable(sid,Integer.parseInt(pfields[1]),
                                    Integer.parseInt(pfields[5]),nc);
                            }
                        }
                        rs1.close();
                        st1.close();
                        
                    }
                }
            }
            rs.close();
            st.close();
            conn.close(); 
            setNewProductTable();
            resetNewProdTFs();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in nextButton");
            e.printStackTrace();
        }
    }//GEN-LAST:event_nextButtonActionPerformed
    public void resetNewProdTFs()
    {
        addSuppIDTF.setText("");
        pidTF.setText("");
        pnameTF.setText("");
        ptypeTF.setText("");
        upriceTF.setText("");
        qtyTF.setText("");
    }
    private void finishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        float total = Float.parseFloat(totalTF.getText());
        int tID = Integer.parseInt(tidTF.getText());
        updateP_O_DBtable(tID,total);
        //opening profile panel
        jPanel3.removeAll();
        jPanel3.repaint();
        jPanel3.revalidate();
        //adding related panel
        jPanel3.add(roughPanel);
        jPanel3.repaint();
        jPanel3.revalidate();
        model.setRowCount(0);
        totalTF.setText("0.0");
        Total=0;
        
    }//GEN-LAST:event_finishButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) transTable.getModel();
        String from = fromdateTF.getText();
        String to = todateTF.getText();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from purchase_order where purchase_date between "+
                    "'"+from+"' and "+"'"+to+"' order by purchase_date asc;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("ptID");
                String date = rs.getString("purchase_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        } 
    }//GEN-LAST:event_searchButtonActionPerformed

    private void viewAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllButtonActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = (DefaultTableModel) transTable.getModel();
        try
        {
            model.setRowCount(0);
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st = conn.createStatement();
            String qry = "select * from purchase_order order by ptID;";
            ResultSet rs = st.executeQuery(qry);
            boolean empty=false;
            while(rs.next())
            {
                empty = true;
                int tid = rs.getInt("ptID");
                String date = rs.getString("purchase_date");
                float total= rs.getFloat("total_cost");
                model.addRow(new Object[]{tid,date,total});
            }
            if(!empty)
                JOptionPane.showMessageDialog(this,"No records found");
            rs.close();
            st.close();
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        } 
    }//GEN-LAST:event_viewAllButtonActionPerformed

    private void viewDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsButtonActionPerformed
        // TODO add your handling code here:
        viewPTransactionDetails ptd = new viewPTransactionDetails();
        ptd.setVisible(true);
        
    }//GEN-LAST:event_viewDetailsButtonActionPerformed

    private void idTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTFActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        model.addRow(new Object[]{"---------","---------","---------","---------"});
        model.addRow(new Object[]{"---------","---------","Total",totalTF.getText()});
        MessageFormat header = new MessageFormat("Purchase No: "+tidTF.getText());
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try
        {
            
            newProdTable.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("cant print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printButtonActionPerformed
    public void insertProduct()
    {
        String pfields[];
        pfields = getProdFields();
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String qry = "insert into product(pID,pname,type,unit_price,quantity,selling_price) "
                                    + "values(?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(qry);
            pst.setInt(1, Integer.parseInt(pfields[1]));
            pst.setString(2, pfields[2]);
            pst.setString(3, pfields[3]);
            pst.setFloat(4, Float.parseFloat(pfields[4]));
            pst.setInt(5, Integer.parseInt(pfields[5]));
            float up = Float.parseFloat(pfields[4]);
            float sp=(float)(up+(up*0.1));
            pst.setFloat(6, sp);
            pst.executeUpdate();
            pst.close();
            conn.close();
            
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in insertProduct()");
            e.printStackTrace();
        }
        
    }
    public void setNewProductTable()
    {
        DefaultTableModel model = (DefaultTableModel) newProdTable.getModel();
        String pfields[];
        pfields = getProdFields();
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            Statement st= conn.createStatement();
            String qry = "select * from product where pID = "+pfields[1]+";";
            ResultSet rs = st.executeQuery(qry);
            while(rs.next())
            {
                String pname=rs.getString("pname");
                float netcost=(Float.parseFloat(pfields[5]) * Float.parseFloat(pfields[4]));
                Total = Total+netcost;
                model.addRow(new Object[]{pname,pfields[5],pfields[4],netcost});
            }
            rs.close();
            st.close();
            conn.close();
            totalTF.setText(Float.toString(Total));
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in setNewProductTable");
            e.printStackTrace();
        }
        
    }
    public void updateS_P_DBtable(int sid, int pid, int qty, float ncost)
    {
        try
        {
           //updating Supplies table in DB. 
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            String qry = "insert into supplies(pID,sID,supply_date) "
                                    + "values(?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(qry);
            pst.setInt(1, pid);
            pst.setInt(2, sid);
            java.sql.Date  sqlDate = new java.sql.Date(new java.util.Date().getTime());
            pst.setDate(3, sqlDate);
            pst.executeUpdate();
            pst.close();
            
            //updating purchase table in DB.
            int tid=Integer.parseInt(tidTF.getText());
            int t=0;
            String qry2 = "select ptID from purchase_order;";
            Statement st2 = conn.createStatement();
            ResultSet rs2 = st2.executeQuery(qry2);
            boolean flag=false;
            while(rs2.next())
            {
                if(tid==rs2.getInt("ptID"))
                {    
                    t=rs2.getInt("ptID");
                    flag=true;
                }
            }
            st2.close();
            rs2.close();
            if(flag==false)
            {  
                updateP_O_DBtable(tid,0);
            }
            String qry1 = "insert into purchase(pID,ptID,quantity,net_cost) "
                                        + "values(?, ?, ?, ?)";
            PreparedStatement pst1 = conn.prepareStatement(qry1);
            pst1.setInt(1, pid);
            pst1.setInt(2, tid);
            pst1.setInt(3, qty);
            pst1.setFloat(4, ncost);
            pst1.executeUpdate();
            pst1.close();
            
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in updateS_P_DBtable");
            e.printStackTrace();
        }
    }
    public void updateP_O_DBtable(int ptid, float tcost)
    {
        try
        {
            Class.forName("java.sql.Driver");
            Connection conn = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/inventory","root","");
            
            if(tcost==0)
            {
                String qry = "insert into purchase_order (ptID,purchase_date,total_cost) values(?,?,?)";
                PreparedStatement pst = conn.prepareStatement(qry);
                pst.setInt(1, ptid);
                java.sql.Date  sqlDate = new java.sql.Date(new java.util.Date().getTime());
                pst.setDate(2, sqlDate);
                pst.setFloat(3, 0);
                pst.executeUpdate();
                pst.close();
            }
            else
            {
                String qry = "update purchase_order set total_cost ="+tcost+"where ptID ="+ptid+";";
                Statement st = conn.createStatement();
                int i = st.executeUpdate(qry);
                if(i!=0)
                    JOptionPane.showMessageDialog(this,"Total cost updated.");
                else
                    JOptionPane.showMessageDialog(this,"Total cost is not updated.");
                st.close();
            }
            conn.close();
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
            JOptionPane.showMessageDialog(this,"exception in updateP_O_DBtable");
            e.printStackTrace();
        }
    }
    public String[] getProdFields()
    {
        String str[] = new String[6];
        str[0]= addSuppIDTF.getText();
        str[1]= pidTF.getText();
        str[2]= pnameTF.getText();
        str[3]= ptypeTF.getText();
        str[4]= upriceTF.getText();
        str[5]= qtyTF.getText();
        return str;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StockManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PurcButton;
    private javax.swing.JLabel StockPurchaseLabel;
    private javax.swing.JButton addNewProButton;
    private javax.swing.JPanel addNewProPanel;
    private javax.swing.JButton addSuppButton;
    private javax.swing.JLabel addSuppIDLable;
    private javax.swing.JTextField addSuppIDTF;
    private javax.swing.JPanel blankPanel;
    private javax.swing.JButton finishButton;
    private javax.swing.JLabel fromLabel;
    private javax.swing.JTextField fromdateTF;
    private javax.swing.JButton fsButton;
    private javax.swing.JTextField idTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton logButton;
    private javax.swing.JButton lsButton;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTable newProdTable;
    private javax.swing.JButton nextButton;
    private javax.swing.JTable pTable;
    private javax.swing.JTextField passTF;
    private javax.swing.JLabel pidLabel;
    private javax.swing.JTextField pidTF;
    private javax.swing.JLabel pnameLabel;
    private javax.swing.JTextField pnameTF;
    private javax.swing.JButton printButton;
    private javax.swing.JButton profButton;
    private javax.swing.JPanel profPanel;
    private javax.swing.JLabel ptypeLabel;
    private javax.swing.JTextField ptypeTF;
    private javax.swing.JPanel purcPanel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JTextField qtyTF;
    private javax.swing.JPanel roughPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton stocButton;
    private javax.swing.JPanel stocPanel;
    private javax.swing.JButton suppButton;
    private javax.swing.JPanel suppPanel;
    private javax.swing.JTable suppTable;
    private javax.swing.JTextField tidTF;
    private javax.swing.JLabel toLabel;
    private javax.swing.JTextField todateTF;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JTextField totalTF;
    private javax.swing.JButton tranButton;
    private javax.swing.JPanel tranPanel;
    private javax.swing.JLabel transLabel;
    private javax.swing.JTable transTable;
    private javax.swing.JLabel upriceLabel;
    private javax.swing.JTextField upriceTF;
    private javax.swing.JButton viewAllButton;
    private javax.swing.JButton viewDetailsButton;
    // End of variables declaration//GEN-END:variables

    private void close()
    {
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

}
